import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { Provider } from "react-redux";
import { store } from "@/store";
import { Providers } from "@/store/providers";
import { ApolloWrapper } from "@/store/apolloClient";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ApolloWrapper>
          <Providers>
          <Header></Header>
        <main className="container mx-auto p-4">{children}</main>
          </Providers>
        </ApolloWrapper>

      </body>
    </html>
  );
}
